version: '3.4'
services:
  mastermind:
    build:
      context: .
    env_file: ./.env
    networks:
      - internal
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080
 
  mysql:
    image: mysql:5.7
    networks:
      - internal
    volumes:
     - ./db/scheme/:/docker-entrypoint-initdb.d
     - ./db/conf/:/etc/mysql/conf.d
     - ../docker-data/mariadb:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=sup3r_p4sswd
     - MYSQL_DATABASE=mastermind
     
  redis:
    image: redis
    networks:
      - internal
      
networks:
  internal:
